<?php

namespace AppBundle\Repository;

/**
 * NamesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NamesRepository extends \Doctrine\ORM\EntityRepository
{

    

}
